apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  ports:
    - port: 12345
      protocol: TCP
      targetPort: 12345
  selector:
    app: search-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deploy
spec:
  selector:
    matchLabels:
      app: search-pod
  template:
    metadata:
      labels:
        app: search-pod
    spec:
      containers:
        - name: search-service-cont
          image: $IMAGE_NAME
          ports:
          - containerPort: 12345
            protocol: TCP
          volumeMounts:
            - name: secret-volume
              mountPath: "/run/secrets/mapbox_token"
              readOnly: true
              subPath: mapbox_token
      volumes:
        - name: secret-volume
          secret:
            secretName: mapbox-access
            items:
              - key: token
                path: mapbox_token