apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  ports:
    - port: 12345
      protocol: TCP
      targetPort: 12345
  selector:
    app: search-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deploy
spec:
  selector:
    matchLabels:
      app: search-pod
  template:
    metadata:
      labels:
        app: search-pod
    spec:
      containers:
        - name: search-service-cont
          env:
          - name: MAPBOX_TOKEN
            valueFrom:
              secretKeyRef:
                name: mapbox-access
                key: token
          image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          ports:
          - containerPort: 12345
            protocol: TCP
