@startuml Search Places Sequence Diagram

actor Client

participant endpoint.SearchEndpoint
participant serviceImpl.SearchServiceProxyImpl
participant serviceImpl.MapBoxPlacesPathBuilder
participant httpClientImpl.HttpClientImpl
participant drogon.HttpClient

== Receiving request and forwarding ==

Client -> endpoint.SearchEndpoint ++ : places()

    endpoint.SearchEndpoint -> serviceImpl.SearchServiceProxyImpl ++ : searchPlaces()

        serviceImpl.SearchServiceProxyImpl -> serviceImpl.MapBoxPlacesPathBuilder ++ : reset()
        return

        serviceImpl.SearchServiceProxyImpl -> serviceImpl.MapBoxPlacesPathBuilder ++ : withBasePath()
        return

        serviceImpl.SearchServiceProxyImpl -> serviceImpl.MapBoxPlacesPathBuilder ++ : withQuery()
        return

        serviceImpl.SearchServiceProxyImpl -> serviceImpl.MapBoxPlacesPathBuilder ++ : withParameter()
        return

        serviceImpl.SearchServiceProxyImpl -> serviceImpl.MapBoxPlacesPathBuilder ++ : build()
        return

        serviceImpl.SearchServiceProxyImpl -> httpClientImpl.HttpClientImpl ++ : sendRequest()

            httpClientImpl.HttpClientImpl -> drogon.HttpClient ++ : sendRequest()
            note right
                Async processing in Drogon main event loop
            end note
            return

        return
    return
return

== Forwarding response ==

drogon.HttpClient ->> httpClientImpl.HttpClientImpl ++ : <callback>
note right
    Async response callback invocation 
end note
    httpClientImpl.HttpClientImpl -> serviceImpl.SearchServiceProxyImpl ++ : <callback>

        serviceImpl.SearchServiceProxyImpl -> endpoint.SearchEndpoint ++ : <callback>

            endpoint.SearchEndpoint -> Client : <callback>
        
        return
    return
return

@enduml
