name: Build service

on: push

jobs:
  build:
    name: Build service
    permissions: write-all
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/map-app-search-service-rel-env
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install git
        run: apt install -y git

      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Debug
        run: |
          echo $PWD
          ls -alh ..
          mkdir buildDbg
          cd buildDbg
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=out -DCONAN_DEPS_PATH=/workspace/search-service-dependencies-rel ..
          make all

      - name: Run coverage
        run: |
          cd buildDbg
          make coverage

      - name: Build Release
        run: |
          mkdir buildRel
          cd buildRel
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=out -DCONAN_DEPS_PATH=../search-service-dependencies-rel ..
          make install
